### ISSUE TITLE
OGR in wheels not distributed with Arrow read/write driver

### ISSUE THREAD

**Issue by kylebarron** [geopandas/pyogrio#215]
I was just curious to see the speed difference between `pyarrow.parquet.read_table` and `pyogrio.raw.read_arrow` to see how much overhead the `read_arrow` had. It appears that the default pyogrio isn't built with the Arrow driver, and I get 

```
'file.parquet' not recognized as a supported file format.
```

I was surprised that Arrow isn't a driver because it still works to _read into Arrow memory_, but I guess that's because the C Data Interface is vendored?

Given that we can use pyarrow this isn't a huge deal and you can close if you wish.

**Comment by jorisvandenbossche** [comment]
Yes, the support for reading _any_ format as an Arrow stream (via the C Data Interface) is implemented natively in GDAL without using any Arrow C++ libraries, and so this is always available once you have GDAL >= 3.6.

On the other hand the the Arrow and Parquet _drivers_ to read actual arrow/parquet files use the Arrow C++ library, and so this needs to be explicitly enabled when GDAL is built, and then also vendored in the wheels in case of pyogrio.

And indeed, since for those two formats (from a geopandas perspective) you can already easily use pyarrow / geopandas.read_parquet, it was 1) not a priority to try to get the wheels building with Arrow, and 2) even a bit unclear if that is worth the increase in size of the wheel.

**Comment by kylebarron** [comment]
Yep that makes sense! I'll close this
