### ISSUE TITLE
Ensure to catch and propagate errors when calling GDALClose

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#221]
See https://github.com/Toblerity/Fiona/issues/1169 (and fix in fiona: https://github.com/Toblerity/Fiona/commit/04ad6c8960c84ee6a2d29acd9e35e79bde193750) for context. 

I think we have the same issue as fiona that we are not checking for errors when "closing" the dataset when writing, while the writing can still go wrong at that point, and so this wouldn't bubble up to users.

**Comment by jorisvandenbossche** [comment]
Although if I run the equivalent pyogrio code from the fiona test case, we already get an error:

```
In [63]: pyogrio.write_dataframe(df, "s3://non-existing-bucket/test.geojson", driver="GeoJSON")
ERROR 4: Failed to create GeoJSON datasource: s3://non-existing-bucket/test.geojson: s3://non-existing-bucket/test.geojson: No such file or directory
...
~/scipy/repos/pyogrio/pyogrio/_io.pyx in pyogrio._io.ogr_write()

~/scipy/repos/pyogrio/pyogrio/_io.pyx in pyogrio._io.ogr_create()

DataSourceError: Failed to create GeoJSON datasource: s3://non-existing-bucket/test.geojson: s3://non-existing-bucket/test.geojson: No such file or directory
```

**Comment by brendan-ward** [comment]
We're getting an error because we aren't properly handling `s3://...` protocol for writing.  We use `get_vsi_path` elsewhere for reading, which converts that to `/vsis3/...`.

If you instead attempt to write `pyogrio.write_dataframe(df, "/vsis3/non-existing-bucket/test.geojson", driver="GeoJSON")`

it fails silently.
(working on a fix now for both issues)
