### ISSUE TITLE
Documentation on where and SQL syntax

### ISSUE THREAD

**Issue by tfardet** [geopandas/pyogrio#276]
I might have missed something, but the documentation link for the `where` keyword did not get me very far.
From what I tested, it seems to work like in GDAL, so [this link](https://gdal.org/user/ogr_sql_dialect.html#where) could be more helpful?

Something that would also be nice is an additional explanation on how to deal with:

* booleans (should one use 0/1, true/false, True/False, something else?)
* potential None/Null/NaN differences and how to deal with them

**Comment by theroggy** [comment]
> I might have missed something, but the documentation link for the where keyword did not get me very far.
From what I tested, it seems to work like in GDAL, so [this link](https://gdal.org/user/ogr_sql_dialect.html#where) could be more helpful?

Indeed, the information in the [page currently being linked to](https://ogdi.sourceforge.net/prop/6.2.CapabilitiesMetadata.html#:~:text=qe_format%3Drestricted_where) isn't up-to-date anymore. It states e.g. that NOT and LIKE are not supported, but a quick test shows that they are.

I also tested some more specific things mentioned on the [OGRSQL page](https://gdal.org/user/ogr_sql_dialect.html#where) (the page you suggest to link to) and you are right that that seems to contain a better and more and up-to-date description of the currently supported syntax.

The reason that page is being linked to is because this is the page being linked to in the relevant [gdal C API documentation](https://gdal.org/api/vector_c_api.html#_CPPv424OGR_L_SetAttributeFilter9OGRLayerHPKc) as well, so I'll log an issue in the gdal issue tracker to suggest the link being changed there as well.

For reference, the script I used to do some validations on the supported syntax:
```
import pyogrio

url = "https://github.com/theroggy/pysnippets/raw/main/pysnippets/pyogrio/polygon-parcel_31370.zip"
wheres = [
    None,
    "LBLHFDTLT LIKE 'Gras%'",
    "LBLHFDTLT LIKE 'gras%'",
    "LBLHFDTLT ILIKE 'gras%'",
    "LBLHFDTLT NOT LIKE 'Gras%'",
    "LBLHFDTLT != 'Grasklaver'",
    "LBLHFDTLT IN ('Hoofdgebouwen', 'Grasklaver')",
]

for where in wheres:
    df = pyogrio.read_dataframe(url, where=where)
    print(f"\nnb_rows with where: {where}: {len(df)}")
    print(df["LBLHFDTLT"].unique())
```

**Comment by theroggy** [comment]
> Something that would also be nice is an additional explanation on how to deal with:

As a general remark, because we'll be changing the link to point to the [OGRSQL page](https://gdal.org/user/ogr_sql_dialect.html#where), it will probably be the way to go to add any additional information regarding the syntax to use is added to that page. Because that page is part of the gdal documentation, the way to go to get any changes applied to it is to open an issue in the [gdal issue tracker](https://github.com/OSGeo/gdal/issues).

> * booleans (should one use 0/1, true/false, True/False, something else?)

Specifically for this remark: I'm not sure if there is a generic answer to your questions/suggestions for clarification. As you probably know, gdal support a lot of file formats and booleans are not very well defined in general. Many file formats don't even support them at all and then you need to fallback to using 0/1,... I didn't do any testing and I might be wrong, but I think it is likely that the only possible answer will be: it depends on the file format.

So personally I think the best way forward would be if you could do some tests on different file formats regarding booleans. Based on those experiences you could open an issue in the gdal issue tracker to suggest some clarifications, if possible.

> * potential None/Null/NaN differences and how to deal with them

Because OGRSQL is an sql dialect, the syntax that is being described there in the [OGRSQL documentation](https://gdal.org/user/ogr_sql_dialect.html#where) is to use "IS NULL" and "IS NOT NULL". As far as I know, the distinction between None and Nan is not a thing in SQL and they both map to NULL.

**Comment by theroggy** [comment]
@tfardet the documentation of the `where` parameter of `read_dataframe` will be updated in the "stable" documentation once a new version of pyogrio will be released. However, you can already have a preview at the "latest" version with this link:
https://pyogrio.readthedocs.io/en/latest/api.html#pyogrio.read_dataframe

I'll close this issue now, but if you think there are still things to be done on the pyogrio side, feel free to reopen it.

**Comment by tfardet** [comment]
Looks good, thanks for your detailed answers!
