### ISSUE TITLE
ENH: support `mask` keyword for compatibility with Fiona

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/pyogrio#277]
Current plan is to use bounding box of mask when reading features with GDAL, then filter using shapely.

The issue is that OGR will give different results if GEOS is or is not compiled into GDAL.  Using shapely afterward ensures precise results.

**Comment by jorisvandenbossche** [comment]
Can we detect when the GDAL in use in compiled with GEOS or not? (I suppose if `get_gdal_geos_version()` is not None?) Because otherwise we could let it depend on that whether we do an additional check with shapely or not?

Other question is also whether we want to do this in pyogrio, or just in geopandas.read_file (where we could pass the bbox to pyogrio, and do the remaining filtering there).

**Comment by theroggy** [comment]
I suppose it is, otherwise it probably wouldn't have come up, but is it a common case that gdal is built without geos? If not, just raising an "unsupported" error if geos is not available might be enough?
