### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [geopandas/pyogrio#311]
Hello!

I may have found a security issue in latest version of [pyogrio](https://pypi.org/project/pyogrio). Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by brendan-ward** [comment]
Is this related to [Fiona #1298](https://github.com/Toblerity/Fiona/issues/1298) and originating from a vulnerability in libwebp as described in [rasterio #2924](https://github.com/rasterio/rasterio/discussions/2924)?

We should probably provide instructions for reporting security issues; I don't see anything listed in the broader GeoPandas documentation.  For now you can report it directly to me (bcward@astutespruce.com).

**Comment by SCH227** [comment]
No, I sent it by email.
I recommend [adding a SECURITY.md](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) file in your repo so reporters have clear instructions on how to handle disclosures.
Thank you for your awesome project!

**Comment by brendan-ward** [comment]
This is related to libcurl linked in via GDAL as part of our wheel-building infrastructure.  Crossref [curl #12026](https://github.com/curl/curl/discussions/12026), details forthcoming on 10/11/2023.  Since the pre-notification of the vulnerability is public, no issues publicly disclosing that much here.
