### ISSUE TITLE
ENH: provide keyword to force promoting mixed singular / multi geometry column to multi geometry type during serialization

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#56]
Geopackages (officially) don't support to have multiple geometry types in a single column. For the points versus lines versus polygons this isn't an issue but for eg. polygons versus multipolygons I don't like this. 

Hence, for layers containing both polygons and multipolygons I tend to convert all polygons tot multipolygons as well and save them in a multipolygon column to get to a conforming geopackage. The alternative is to use the generic GEOMETRY as column type, but then you don't have any clue which data is in the column.

Eg. in ogr2ogr it is possible to "force" conversion to specific geometry types using the -nlt parameter = MULTIPOLYGON | PROMOTE_TO_MULTI.

Would you consider supporting this one way or the other in pyogrio?

PS: now I do the conversion in python upfront, but for large files this takes as long as writing the file, which is a bit of a pity...

**Comment by brendan-ward** [comment]
Other formats (e.g., FlatGeobuff) reject mixed singular and multi geometries, so over the long term there may be some benefit to providing a keyword parameter to force conversion to multi geometry types.

However, for the short term, the best way is to handle this prior to serializing data.  If you have `pygeos' available and only convert singular to multi, it should be fairly fast.

Here is the function I use in my own work to do this for mixed singular/multi polygons => multipolygons, using pygeos and numpy, in case it helps.

```
import pygeos as pg
import numpy as np

def to_multipolygon(geometries):
    """Convert single part polygons to multipolygons

    Parameters
    ----------
    geometries : ndarray of pygeos geometries
        can be mixed polygon and multipolygon types

    Returns
    -------
    ndarray of pygeos geometries, all multipolygon types
    """
    ix = pg.get_type_id(geometries) == 3
    if ix.sum():
        geometries = geometries.copy()
        geometries[ix] = np.apply_along_axis(
            pg.multipolygons, arr=(np.expand_dims(geometries[ix], 1)), axis=1
        )

    return geometries
```

(note: you could also update the geometry in place instead of making a copy)

**Comment by theroggy** [comment]
OK.

Thanks for the code! I never used pygeos directly before, but it seems worth it: your implementation is 5 times faster than mine was using shapely. 11 secs for the conversion to multipolygons versus 53 secs for my standard test file (~600.000 polygons).
