### ISSUE TITLE
Writing a dataframe with a string column with np.nan value gives an error

### ISSUE THREAD

**Issue by theroggy** [geopandas/pyogrio#60]
Writing a dataframe with string column with np.nan values in it gives an Exception: ValueError: "Could not encode value 'nan' in field 'PM' to string".

The following code triggers the Exception:
```
import geopandas as gpd
import numpy as np
import pyogrio
import shapely.geometry

output_path = r"C:\temp\test_write_nan.gpkg"
test_gdf = gpd.GeoDataFrame(
        geometry=[
                shapely.geometry.Polygon(shell=[(1, 1), (1, 2), (2, 2), (2, 1), (1, 1)]),
                shapely.geometry.Polygon(shell=[(1, 1), (1, 2), (2, 2), (2, 1), (1, 1)])],
        crs="epsg:31370")
test_gdf["PM"] = "foo"
test_gdf.at[1, "PM"] = np.nan
pyogrio.write_dataframe(test_gdf, output_path)
```

**Comment by brendan-ward** [comment]
This is a bigger issue of the DataFrame having mixed data types within a single column.  In order to serialize those, we need them to be a consistent type.

`np.nan` is not a string value, but is used as a sentinal value that the value is actually NULL.  We may be able to use [`OGR_F_SetFieldNull `](https://gdal.org/api/vector_c_api.html#ogr__api_8h_1a090a6a8d699d4eed977ce9fcf028137a) to set the field as NULL when serializing that value, regardless of the data type of that field.

**Comment by jorisvandenbossche** [comment]
We already use that function, so I think it is a matter of generalizing this `is None` check:

https://github.com/geopandas/pyogrio/blob/d243d0263e5aadaf21ff6fd4864d630610cfabdc/pyogrio/_io.pyx#L1280-L1281

We can generalize that for np.nan, but also for pd.NA. 
Although we might want to check the performance penalty for that, since pd.NA is a plain python object.
