### ISSUE TITLE
Linux wheels require CURL_CA_BUNDLE to be set

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#66]
> The curl issue sounds like maybe a certificate issue. Perhaps you need to run

Looking for the error in GDAL context, I found some issues from rasterio/fiona: see the explanation at https://github.com/sgillies/frs-wheel-builds/issues/12 / https://github.com/rasterio/rasterio/issues/1737, and this is actually documented for rasterio at https://github.com/rasterio/rasterio/blob/master/README.rst#ssl-certs. 
And indeed, if I do `CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt pytest --pyargs pyogrio` all tests pass.

It seems that fiona fixed this by setting that environment variable for you: https://github.com/Toblerity/Fiona/commit/5743a9600e80ab033ecb9b9275c0c3f954349e21 
I think we can probably do something similar here. Although we can maybe just do it for wheels, and not in general. And in case of manylinux wheels (although can we detect this?) we could maybe even harcode the value, instead of adding `certifi` as an additional requirement.

_Originally posted by @jorisvandenbossche in https://github.com/geopandas/pyogrio/issues/55#issuecomment-1068224847_

**Comment by jorisvandenbossche** [comment]
For now, we set this environment variable when testing the wheels:

https://github.com/geopandas/pyogrio/blob/b78e0a66260f093e33f9b41e95c83d60b93f88b1/.github/workflows/release.yml#L179-L183

It would be nice to automatically set this, in case of using a wheel on linux, using the optional `certifi` (like fiona does), and then we can make `certifi` a linux-only dependency?

**Comment by brendan-ward** [comment]
> It would be nice to automatically set this, in case of using a wheel on linux, using the optional certifi (like fiona does), and then we can make certifi a linux-only dependency

Agreed.  Other than I think Fiona ran into some issues with it being optional?  But also perhaps we can be even more optional with this, since it is only needed for I/O across the network.  E.g., if on linux, and `CURL_CA_BUNDLE` is not set, try to import `certifi` and use that.  If not available, then emit a warning that network I/O will not be supported without either setting `CURL_CA_BUNDLE` or installing `certifi`.

**Comment by jorisvandenbossche** [comment]
See https://github.com/OSGeo/gdal/pull/3025, for recent versions of GDAL we should use the `GDAL_CURL_CA_BUNDLE` env variable

**Comment by snowman2** [comment]
Also need to set `PROJ_CURL_CA_BUNDLE` (https://github.com/OSGeo/PROJ/issues/2320)

**Comment by snowman2** [comment]
Side note: certifi is used by 830k python libraries and counting (https://github.com/certifi/python-certifi). It is a pure python library with no dependencies. Due to its lightweight nature and its high probability of being python environments, it may be worth adding as a main dependency to pyogrio as it will make things simpler.

**Comment by brendan-ward** [comment]
Using `certifi` per [Fiona #1095](https://github.com/Toblerity/Fiona/pull/1095) seems reasonable to me.
